### PR TITLE
Added openSUSE Tumbleweed KDE Live

### PR DESCRIPTION
**Pull request by knurpht**
As per title.

### CODE REVIEW

**Comment by fransvanberckel** [comment]
But there is no definition of $linux and $initrd set.

**Comment by fransvanberckel** [comment]
And what about isofile?

**Comment by linuxfriendly** [comment]
Added the initial commit anyway and added the suse isofile directive. Needs testing

**Comment by linuxfriendly** [comment]
Tested & working. Git-repo now has a working suse bootcd added. Rework later as a livecd

**Pull request merged**
